apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: kiranreddykr7/medicure-service:latest
          ports:
            - containerPort: 8081   
          readinessProbe:
            httpGet:
              path: /api/searchDoctor/John
              port: 8081           
            initialDelaySeconds: 10
            periodSeconds: 10


