apiVersion: v1
kind: Service
metadata:
  name: h2-console-service
spec:
  selector:
    app: medicure
  type: NodePort
  ports:
    - name: http       
      port: 8081
      targetPort: 8081
      nodePort: 30003
    - name: tcp        
      port: 9092
      targetPort: 9092
      nodePort: 30005
 