apiVersion: v1
kind: Service
metadata:
  name: h2-console-service
  namespace: default
spec:
  selector:
    app: medicure
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
  type: NodePort
